include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

variables:
    BUNDLE: "gitg-git.flatpak"

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: "org.gnome.gitgDevel.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "gitg"
    MESON_ARGS: "-Ddeprecations=true --buildtype=debugoptimized -Dprofile=development"
    APP_ID: "org.gnome.gitgDevel"

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'
