include: 
  - project: "gnome/citemplates"
    ref: "master"
    file: "flatpak/flatpak_ci_initiative.yml"
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      dist-job-name: "flatpak"

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: "org.gnome.gitgDevel.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "gitg"
    APP_ID: "org.gnome.gitgDevel"
    BUNDLE: "gitg-git.flatpak"


nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
