#!/bin/bash

. $(dirname "$0")/env

# Install brew if necessary
if [ ! -f "$d/install/bin/brew" ]; then
	mkdir -p "$d/install"
	bsha1=375efe09455218d9929e41f16317074ccdf50f2a

	(
		cd "$d/install"
		curl -L -o $bsha1.zip https://github.com/Homebrew/brew/archive/$bsha1.zip
		unzip $bsha1.zip
		rm -f $bsha1.zip

		shopt -s dotglob nullglob
		mv "brew-$bsha1"/* .
		shopt -u dotglob

		rmdir "brew-$bsha1"
	)
fi

# Link tap if necessary
tap="$d/install/Library/Taps/gnome/homebrew-gitg"

if [ ! -d "$tap" ]; then
	mkdir -p "$d/install/Library/Taps/gnome"
	ln -s "$root/osx/Taps/gitg" "$tap"
fi

exec "$lbrew" install --dependencies-only --HEAD gnome/gitg/gitg
